blank_issues_enabled: false
contact_links:
  - name: Add location
    url: https://btcmap.org/add-location
    about: Please use the form on our website.
  - name: Verify location
    url: https://btcmap.org/verify-location
    about: Please use the form on our website.
